// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtxzecwowouhgakrspic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0eHplY3dvd291aGdha3JzcGljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMTgzNDIsImV4cCI6MjA3MzU5NDM0Mn0.6Gq_91A0AWqaQ6gAJ1ZozIT8r_YxTBKr-Ezmo7cVhi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});